### ISSUE TITLE
Register Bug

### ISSUE THREAD

**Issue by matt456** [hcs64/boot_stub#1]
Hi, thanks for this great project. Proving super useful!

I think I've found a slight bug in boot_stub.asm:
constant Cause(16)
should be
constant Cause(13)

The Cause register is 13 not 16: http://en64.shoutwiki.com/wiki/Registers
I'm currently using ipl3hasher to get a match for the stub with that change. I'll paste it here when done!

**Comment by matt456** [comment]
`0xB2DEC2CE,
    0x1091,`

That's the new hash to go at the end of the file, byte 0x42 in boot_stub.bin changes to 0x68 from 0x80 with the recompilation.

**Comment by hcs64** [comment]
Good catch, and thanks for re-colliding the hash! I'll make the change when I can get the HW set up again to double-check. I'm glad to see someone making use of this, are you working on your own bootcode?
